version: '3'
services:

  backend:
    build: flask
    container_name: backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      PORT: 5000
      APP_ENV: "prod"
      APP_DEBUG: "True"
      APP_PORT: 5000
    volumes:
      - ./flask:/src
    depends_on:
      - mongo
    networks:
      - frontend
      - backend

  mongo:
    image: mongo
    container_name: mongo
  
  web: 
    image: nginx:latest
    restart: always
    volumes:
      - ./nginx/web:/usr/share/nginx/html
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
    networks:
      - frontend
    
networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

volumes:
  mongodbdata:
    driver: local
  appdata:
    driver: local
  nginxdata:
    driver: local
  tododata:
    driver: local 
  share:
    driver: local
